# Generated by Django 4.2.9 on 2024-03-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='lett_er',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='signal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plugboard',
            name='pairs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='plugboard',
            name='signal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reflect',
            name='right',
            field=models.CharField(default='ABCDEFGHIJKLMNOPQRSTUVWXYZ', max_length=26),
        ),
        migrations.AddField(
            model_name='reflect',
            name='signal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rotors_i',
            name='lett_er',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='rotors_i',
            name='n',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rotors_i',
            name='right',
            field=models.CharField(default='ABCDEFGHIJKLMNOPQRSTUVWXYZ', max_length=26),
        ),
        migrations.AddField(
            model_name='rotors_i',
            name='signal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rotors_ii',
            name='lett_er',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='rotors_ii',
            name='n',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rotors_ii',
            name='right',
            field=models.CharField(default='ABCDEFGHIJKLMNOPQRSTUVWXYZ', max_length=26),
        ),
        migrations.AddField(
            model_name='rotors_ii',
            name='signal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rotors_iii',
            name='lett_er',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='rotors_iii',
            name='n',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rotors_iii',
            name='right',
            field=models.CharField(default='ABCDEFGHIJKLMNOPQRSTUVWXYZ', max_length=26),
        ),
        migrations.AddField(
            model_name='rotors_iii',
            name='signal',
            field=models.IntegerField(default=0),
        ),
    ]
