# Generated by Django 4.2.9 on 2024-03-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_rename_lett_er_keyboard_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotors_i',
            name='notch',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
