# Generated by Django 4.2.9 on 2024-03-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_rotors_i_notch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='rotors_i',
            name='notch',
        ),
    ]
