# Generated by Django 4.2.9 on 2024-03-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_inventory_remove_rotors_i_notch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rotors_I',
            new_name='Rotor_I',
        ),
        migrations.RenameModel(
            old_name='Rotors_II',
            new_name='Rotor_II',
        ),
        migrations.RenameModel(
            old_name='Rotors_III',
            new_name='Rotor_III',
        ),
        migrations.AddField(
            model_name='inventory',
            name='Keys',
            field=models.CharField(default='DOG', max_length=3),
        ),
    ]
