# Generated by Django 4.2.9 on 2024-03-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_rename_rotors_i_rotor_i_rename_rotors_ii_rotor_ii_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reflect',
            new_name='Reflector',
        ),
    ]
