# Generated by Django 4.2.10 on 2024-06-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_remove_rotor_i_letter_remove_rotor_i_signal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='plugboard',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='reflector',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='rotor_i',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='rotor_iii',
            name='user_id',
        ),
    ]
